name: nano_health
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  provider: ^6.0.5
  get_it: ^7.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  pretty_dio_logger: ^1.3.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/